### ISSUE TITLE
Two common errors

### ISSUE THREAD

**Issue by maier-m** [cboettig/eml2#7]
There are two common vague errors that appear often when working in eml2.
1. `Error: parse error: trailing garbage ...`
2. `Error: C stack usage  XXXXXXX is too close to the limit`

The following code illustrates both.
```
f <- system.file("xsd/test", "eml-datasetWithUnits.xml", package = "EML")
eml <- eml2::read_eml(f)
eml2::eml_get(eml, "attributeName")
eml2::eml_get(eml$dataset$dataTable$attributeList$attribute[[1]], "attributeName")
```
I don't believe the behavior is isolated to `eml_get` this just serves as a minimal reproducible error.

**Comment by cboettig** [comment]
Thanks for the reproducible examples! I'll take a look.

**Comment by cboettig** [comment]
@maier-m Okay, I think this should be fixed in `master` (you'll have to reinstall `emld` from GitHub too, though I bumped the version requirement here so `install_github("cboettig/eml2")` should do that automatically...

This should fix the minimal examples above, but I suspect these errors may still appear elsewhere. Please continue to file reports for any reproducible errors like these you get, having an example to work from makes things much easier to debug.  

The second error (`C stack usage ...`) occurs whenever I screw up a recursive function and permit an infinite loop for some edge case, and there's quite a lot of recursive functions.  The first error is more specific to `jq` usage which only appears in two functions (`eml_get` and `get_unitType`, so I think should be squashed...
